apiVersion: apps/v1
kind: Deployment
metadata:
  name: enc-key-sync-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: enc-key-sync-operator
  template:
    metadata:
      labels:
        name: enc-key-sync-operator
    spec:
      serviceAccountName: enc-key-sync-operator
      containers:
        - name: enc-key-sync-operator
          # Replace this with the built image name
          image: docker.io/lumjjb/enc-key-sync-operator:v0.0.1
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "enc-key-sync-operator"
