apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: enc-key-sync-catalog
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: docker.io/lumjjb/enc-key-sync-operator-catalog:v0.0.1
  displayName: Encrypted Key Sync Catalog
  updateStrategy:
    registryPoll: 
      interval: 30m
