apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: enc-key-sync
spec: {}
status: {}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: enc-key-sync
  namespace: enc-key-sync
  labels:
    app: enc-key-sync
spec:
  selector:
    matchLabels:
      name: enc-key-sync
  template:
    metadata:
      labels:
        name: enc-key-sync
    spec:
      containers:
      - name: enc-key-sync
        image: lumjjb/keysync:latest
        imagePullPolicy: Always
        args:
        - -dir
        - /keys
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: hostkeys
          mountPath: /keys
      terminationGracePeriodSeconds: 30
      volumes:
      - name: hostkeys
        hostPath:
          path: /etc/crio/keys
          type: DirectoryOrCreate
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: enc-key-sync-r
  namespace: enc-key-sync
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: enc-key-sync-rb
  namespace: enc-key-sync
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: enc-key-sync-r
  apiGroup: rbac.authorization.k8s.io
