apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: enc-key-sync
spec: {}
status: {}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: enc-key-sync
  namespace: enc-key-sync
  labels:
    app: enc-key-sync
spec:
  selector:
    matchLabels:
      name: enc-key-sync
  template:
    metadata:
      labels:
        name: enc-key-sync
    spec:
      serviceAccountName: enc-key-sync-sa
      containers:
      - name: enc-key-sync
        image: lumjjb/keysync:latest
        imagePullPolicy: Always
        args:
        - -dir
        - /keys
        - -keyprotectConfig
        - /kpconfig/config.json
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: hostkeys
          mountPath: /keys
        - name: keyprotect-config
          mountPath: /kpconfig
      terminationGracePeriodSeconds: 30
      volumes:
      - name: hostkeys
        hostPath:
          path: /etc/crio/keys/enc-key-sync
          type: DirectoryOrCreate
      - name: keyprotect-config
        secret:
          secretName: keyprotect-config

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: enc-key-sync-r
  namespace: enc-key-sync
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: enc-key-sync-rb
  namespace: enc-key-sync
subjects:
- kind: ServiceAccount
  name: enc-key-sync-sa
roleRef:
  kind: Role
  name: enc-key-sync-r
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: enc-key-sync
  creationTimestamp: null
  name: enc-key-sync-sa
---
apiVersion: v1
kind: Secret
metadata:
  name: keyprotect-config
  namespace: enc-key-sync
type: Opaque
stringData:
  config.json: |
      {
      "keyprotect-url":"https://us-south.kms.cloud.ibm.com",
      "instance-id": "your bluemix instance ID",
      "apikey": "apikey-for-accessing-unwrap-api"
      }
