#apiVersion: v1
#kind: Namespace
#metadata:
#  creationTimestamp: null
#  name: {{ .Release.Namespace }}
#spec: {}
#status: {}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: enc-key-sync
  namespace: {{ .Release.Namespace }}
  labels:
    app: enc-key-sync
spec:
  selector:
    matchLabels:
      name: enc-key-sync
  template:
    metadata:
      labels:
        name: enc-key-sync
    spec:
      serviceAccountName: enc-key-sync-sa
      containers:
      - name: enc-key-sync
        image: lumjjb/keysync:latest
        imagePullPolicy: Always
        args:
        - -dir
        - /keys
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: hostkeys
          mountPath: /keys
      terminationGracePeriodSeconds: 30
      volumes:
      - name: hostkeys
        hostPath:
          path: {{ .Values.keyPath }}
          type: DirectoryOrCreate
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: enc-key-sync-r
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
# Used for openshift to mount hostPath
- apiGroups:
   - security.openshift.io
  resources:
   - securitycontextconstraints
  verbs:
   - use
  resourceNames:
   - hostmount-anyuid
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: enc-key-sync-rb
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: enc-key-sync-sa
roleRef:
  kind: Role
  name: enc-key-sync-r
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  creationTimestamp: null
  name: enc-key-sync-sa
