name: Go

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:

  Test:
    env:
      GOLANGCI_LINT_VERSION: v1.32.2
      GOSEC_VERSION: v2.5.0

    name: CI Checks
    runs-on: self-hosted,go
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install dependancies
      run: apt-get update && apt-get upgrade -y && apt-get install -y libseccomp-dev gnutils-bin

    - name: Install golangci lint
      run: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin ${GOLANGCI_LINT_VERSION}

    - name: Install gosec
      run: curl -sfL https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s -- -b $(go env GOPATH)/bin ${GOSEC_VERSION}

    - name: Test
      run: make check
