name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    env:
      GOLANGCI_LINT_VERSION: v1.54.2
      GOSEC_VERSION: v2.17.0


    name: Test
    runs-on: [self-hosted,go]
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install dependancies
      run: |
        apt-get update
        apt-get upgrade -y
        apt-get install -y libseccomp-dev gnutls-bin

    - name: Install golangci lint
      run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin ${GOLANGCI_LINT_VERSION}

    - name: Install gosec
      run: curl -sfL https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s -- -b $(go env GOPATH)/bin ${GOSEC_VERSION}

    - name: Test
      run: |
        export PATH=$PATH:/usr/local/go/bin/
        make check
