name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    env:
      GOLANGCI_LINT_VERSION: v1.63.4
      GOSEC_VERSION: v2.22.0


    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        check-latest: true

    - run: go version

    - name: Install dependancies
      run: |
        sudo apt-get update
        sudo apt-get upgrade -y
        sudo apt-get install -y libseccomp-dev gnutls-bin

    - name: Install golangci lint
      run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin ${GOLANGCI_LINT_VERSION}

    - name: Install gosec
      run: curl -sfL https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s -- -b $(go env GOPATH)/bin ${GOSEC_VERSION}

    - name: Test
      run: |
        export PATH=$PATH:/usr/local/go/bin/
        make check
